Add TrainingDataWithPremises Extraction
cmu-l3/ntp-toolkit pull request #2
Opened 2024-08-06 16:11 UTC by JOSHCLUNE

2024-08-08 13:53 UTC, wellecks commented on scripts/run_pipeline.py
> +    # _run_cmd(
Perhaps we can add a command line flag to determine which of these is run (rather than commenting out)

2024-08-08 13:55 UTC, wellecks requested changes
Left a comment about a command-line option for `run_pipeline.py`. Otherwise this looks great, thanks!

2024-08-08 13:55 UTC, wellecks commented
Also, could you add a short description of the new commands to the readme?

2024-08-09 01:20 UTC, JOSHCLUNE commented
I've added command-line options for run_pipeline and updated the README to explain them in the most recent commit. Further additions (such as adding a field for all premises used for the current declId proof or a field for all premises from the current state to the end of the goal) will be handled in a later PR once I am able to address them. Let me know if there are any additional issues, thanks.

2024-08-09 14:05 UTC, wellecks commented
Awesome, thanks!

2024-08-09 14:05 UTC, merged